// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/payment_gateway.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentGatewayPort is a mock of PaymentGatewayPort interface.
type MockPaymentGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentGatewayPortMockRecorder
}

// MockPaymentGatewayPortMockRecorder is the mock recorder for MockPaymentGatewayPort.
type MockPaymentGatewayPortMockRecorder struct {
	mock *MockPaymentGatewayPort
}

// NewMockPaymentGatewayPort creates a new mock instance.
func NewMockPaymentGatewayPort(ctrl *gomock.Controller) *MockPaymentGatewayPort {
	mock := &MockPaymentGatewayPort{ctrl: ctrl}
	mock.recorder = &MockPaymentGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentGatewayPort) EXPECT() *MockPaymentGatewayPortMockRecorder {
	return m.recorder
}

// CreateInvoice mocks base method.
func (m *MockPaymentGatewayPort) CreateInvoice(ctx context.Context, input model.CreatePaymentInput) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, input)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockPaymentGatewayPortMockRecorder) CreateInvoice(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockPaymentGatewayPort)(nil).CreateInvoice), ctx, input)
}
