// Code generated by MockGen. DO NOT EDIT.
// Source: content.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContentDatabasePort is a mock of ContentDatabasePort interface.
type MockContentDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockContentDatabasePortMockRecorder
}

// MockContentDatabasePortMockRecorder is the mock recorder for MockContentDatabasePort.
type MockContentDatabasePortMockRecorder struct {
	mock *MockContentDatabasePort
}

// NewMockContentDatabasePort creates a new mock instance.
func NewMockContentDatabasePort(ctrl *gomock.Controller) *MockContentDatabasePort {
	mock := &MockContentDatabasePort{ctrl: ctrl}
	mock.recorder = &MockContentDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentDatabasePort) EXPECT() *MockContentDatabasePortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockContentDatabasePort) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContentDatabasePortMockRecorder) Delete(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContentDatabasePort)(nil).Delete), key)
}

// FindByKey mocks base method.
func (m *MockContentDatabasePort) FindByKey(key string) (*model.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", key)
	ret0, _ := ret[0].(*model.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockContentDatabasePortMockRecorder) FindByKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockContentDatabasePort)(nil).FindByKey), key)
}

// Upsert mocks base method.
func (m *MockContentDatabasePort) Upsert(content *model.Content) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockContentDatabasePortMockRecorder) Upsert(content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockContentDatabasePort)(nil).Upsert), content)
}
