// Code generated by MockGen. DO NOT EDIT.
// Source: whatsapp.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWhatsAppMessagePort is a mock of WhatsAppMessagePort interface.
type MockWhatsAppMessagePort struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppMessagePortMockRecorder
}

// MockWhatsAppMessagePortMockRecorder is the mock recorder for MockWhatsAppMessagePort.
type MockWhatsAppMessagePortMockRecorder struct {
	mock *MockWhatsAppMessagePort
}

// NewMockWhatsAppMessagePort creates a new mock instance.
func NewMockWhatsAppMessagePort(ctrl *gomock.Controller) *MockWhatsAppMessagePort {
	mock := &MockWhatsAppMessagePort{ctrl: ctrl}
	mock.recorder = &MockWhatsAppMessagePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsAppMessagePort) EXPECT() *MockWhatsAppMessagePortMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWhatsAppMessagePort) Send(target, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", target, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWhatsAppMessagePortMockRecorder) Send(target, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWhatsAppMessagePort)(nil).Send), target, message)
}
