// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentDatabasePort is a mock of PaymentDatabasePort interface.
type MockPaymentDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentDatabasePortMockRecorder
}

// MockPaymentDatabasePortMockRecorder is the mock recorder for MockPaymentDatabasePort.
type MockPaymentDatabasePortMockRecorder struct {
	mock *MockPaymentDatabasePort
}

// NewMockPaymentDatabasePort creates a new mock instance.
func NewMockPaymentDatabasePort(ctrl *gomock.Controller) *MockPaymentDatabasePort {
	mock := &MockPaymentDatabasePort{ctrl: ctrl}
	mock.recorder = &MockPaymentDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentDatabasePort) EXPECT() *MockPaymentDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentDatabasePort) Create(payment *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentDatabasePortMockRecorder) Create(payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Create), payment)
}

// FindByFilter mocks base method.
func (m *MockPaymentDatabasePort) FindByFilter(filter model.PaymentFilter) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockPaymentDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockPaymentDatabasePort) FindByID(id string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByID), id)
}

// FindByOrderID mocks base method.
func (m *MockPaymentDatabasePort) FindByOrderID(orderID string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", orderID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockPaymentDatabasePortMockRecorder) FindByOrderID(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockPaymentDatabasePort)(nil).FindByOrderID), orderID)
}

// MarkAsPaid mocks base method.
func (m *MockPaymentDatabasePort) MarkAsPaid(orderID, paymentType, midtransID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPaid", orderID, paymentType, midtransID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPaid indicates an expected call of MarkAsPaid.
func (mr *MockPaymentDatabasePortMockRecorder) MarkAsPaid(orderID, paymentType, midtransID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPaid", reflect.TypeOf((*MockPaymentDatabasePort)(nil).MarkAsPaid), orderID, paymentType, midtransID)
}

// Update mocks base method.
func (m *MockPaymentDatabasePort) Update(payment *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentDatabasePortMockRecorder) Update(payment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentDatabasePort)(nil).Update), payment)
}

// UpdateStatus mocks base method.
func (m *MockPaymentDatabasePort) UpdateStatus(orderID, status, paymentType, midtransID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", orderID, status, paymentType, midtransID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPaymentDatabasePortMockRecorder) UpdateStatus(orderID, status, paymentType, midtransID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPaymentDatabasePort)(nil).UpdateStatus), orderID, status, paymentType, midtransID)
}
