// Code generated by MockGen. DO NOT EDIT.
// Source: tenant.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "eduvera/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTenantDatabasePort is a mock of TenantDatabasePort interface.
type MockTenantDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDatabasePortMockRecorder
}

// MockTenantDatabasePortMockRecorder is the mock recorder for MockTenantDatabasePort.
type MockTenantDatabasePortMockRecorder struct {
	mock *MockTenantDatabasePort
}

// NewMockTenantDatabasePort creates a new mock instance.
func NewMockTenantDatabasePort(ctrl *gomock.Controller) *MockTenantDatabasePort {
	mock := &MockTenantDatabasePort{ctrl: ctrl}
	mock.recorder = &MockTenantDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDatabasePort) EXPECT() *MockTenantDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantDatabasePort) Create(tenant *model.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantDatabasePortMockRecorder) Create(tenant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantDatabasePort)(nil).Create), tenant)
}

// FindByFilter mocks base method.
func (m *MockTenantDatabasePort) FindByFilter(filter model.TenantFilter) ([]model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", filter)
	ret0, _ := ret[0].([]model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockTenantDatabasePortMockRecorder) FindByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockTenantDatabasePort)(nil).FindByFilter), filter)
}

// FindByID mocks base method.
func (m *MockTenantDatabasePort) FindByID(id string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTenantDatabasePortMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTenantDatabasePort)(nil).FindByID), id)
}

// FindBySubdomain mocks base method.
func (m *MockTenantDatabasePort) FindBySubdomain(subdomain string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubdomain", subdomain)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubdomain indicates an expected call of FindBySubdomain.
func (mr *MockTenantDatabasePortMockRecorder) FindBySubdomain(subdomain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubdomain", reflect.TypeOf((*MockTenantDatabasePort)(nil).FindBySubdomain), subdomain)
}

// SubdomainExists mocks base method.
func (m *MockTenantDatabasePort) SubdomainExists(subdomain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubdomainExists", subdomain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubdomainExists indicates an expected call of SubdomainExists.
func (mr *MockTenantDatabasePortMockRecorder) SubdomainExists(subdomain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubdomainExists", reflect.TypeOf((*MockTenantDatabasePort)(nil).SubdomainExists), subdomain)
}

// Update mocks base method.
func (m *MockTenantDatabasePort) Update(tenant *model.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantDatabasePortMockRecorder) Update(tenant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantDatabasePort)(nil).Update), tenant)
}

// UpdateStatus mocks base method.
func (m *MockTenantDatabasePort) UpdateStatus(id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTenantDatabasePortMockRecorder) UpdateStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTenantDatabasePort)(nil).UpdateStatus), id, status)
}
