// Code generated by MockGen. DO NOT EDIT.
// Source: registry_database.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	sql "database/sql"
	outbound_port "prabogo/internal/port/outbound"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabasePort is a mock of DatabasePort interface.
type MockDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePortMockRecorder
}

// MockDatabasePortMockRecorder is the mock recorder for MockDatabasePort.
type MockDatabasePortMockRecorder struct {
	mock *MockDatabasePort
}

// NewMockDatabasePort creates a new mock instance.
func NewMockDatabasePort(ctrl *gomock.Controller) *MockDatabasePort {
	mock := &MockDatabasePort{ctrl: ctrl}
	mock.recorder = &MockDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePort) EXPECT() *MockDatabasePortMockRecorder {
	return m.recorder
}

// AuditLog mocks base method.
func (m *MockDatabasePort) AuditLog() outbound_port.AuditLogDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuditLog")
	ret0, _ := ret[0].(outbound_port.AuditLogDatabasePort)
	return ret0
}

// AuditLog indicates an expected call of AuditLog.
func (mr *MockDatabasePortMockRecorder) AuditLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditLog", reflect.TypeOf((*MockDatabasePort)(nil).AuditLog))
}

// Client mocks base method.
func (m *MockDatabasePort) Client() outbound_port.ClientDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(outbound_port.ClientDatabasePort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDatabasePortMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDatabasePort)(nil).Client))
}

// Content mocks base method.
func (m *MockDatabasePort) Content() outbound_port.ContentDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Content")
	ret0, _ := ret[0].(outbound_port.ContentDatabasePort)
	return ret0
}

// Content indicates an expected call of Content.
func (mr *MockDatabasePortMockRecorder) Content() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Content", reflect.TypeOf((*MockDatabasePort)(nil).Content))
}

// Disbursement mocks base method.
func (m *MockDatabasePort) Disbursement() outbound_port.DisbursementDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disbursement")
	ret0, _ := ret[0].(outbound_port.DisbursementDatabasePort)
	return ret0
}

// Disbursement indicates an expected call of Disbursement.
func (mr *MockDatabasePortMockRecorder) Disbursement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disbursement", reflect.TypeOf((*MockDatabasePort)(nil).Disbursement))
}

// DoInTransaction mocks base method.
func (m *MockDatabasePort) DoInTransaction(txFunc outbound_port.InTransaction) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTransaction", txFunc)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoInTransaction indicates an expected call of DoInTransaction.
func (mr *MockDatabasePortMockRecorder) DoInTransaction(txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTransaction", reflect.TypeOf((*MockDatabasePort)(nil).DoInTransaction), txFunc)
}

// ERapor mocks base method.
func (m *MockDatabasePort) ERapor() outbound_port.ERaporDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ERapor")
	ret0, _ := ret[0].(outbound_port.ERaporDatabasePort)
	return ret0
}

// ERapor indicates an expected call of ERapor.
func (mr *MockDatabasePortMockRecorder) ERapor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ERapor", reflect.TypeOf((*MockDatabasePort)(nil).ERapor))
}

// Notification mocks base method.
func (m *MockDatabasePort) Notification() outbound_port.NotificationDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notification")
	ret0, _ := ret[0].(outbound_port.NotificationDatabasePort)
	return ret0
}

// Notification indicates an expected call of Notification.
func (mr *MockDatabasePortMockRecorder) Notification() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notification", reflect.TypeOf((*MockDatabasePort)(nil).Notification))
}

// Payment mocks base method.
func (m *MockDatabasePort) Payment() outbound_port.PaymentDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payment")
	ret0, _ := ret[0].(outbound_port.PaymentDatabasePort)
	return ret0
}

// Payment indicates an expected call of Payment.
func (mr *MockDatabasePortMockRecorder) Payment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payment", reflect.TypeOf((*MockDatabasePort)(nil).Payment))
}

// PesantrenDashboard mocks base method.
func (m *MockDatabasePort) PesantrenDashboard() outbound_port.PesantrenDashboardPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PesantrenDashboard")
	ret0, _ := ret[0].(outbound_port.PesantrenDashboardPort)
	return ret0
}

// PesantrenDashboard indicates an expected call of PesantrenDashboard.
func (mr *MockDatabasePortMockRecorder) PesantrenDashboard() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PesantrenDashboard", reflect.TypeOf((*MockDatabasePort)(nil).PesantrenDashboard))
}

// SDM mocks base method.
func (m *MockDatabasePort) SDM() outbound_port.SDMDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SDM")
	ret0, _ := ret[0].(outbound_port.SDMDatabasePort)
	return ret0
}

// SDM indicates an expected call of SDM.
func (mr *MockDatabasePortMockRecorder) SDM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SDM", reflect.TypeOf((*MockDatabasePort)(nil).SDM))
}

// SPP mocks base method.
func (m *MockDatabasePort) SPP() outbound_port.SPPDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SPP")
	ret0, _ := ret[0].(outbound_port.SPPDatabasePort)
	return ret0
}

// SPP indicates an expected call of SPP.
func (mr *MockDatabasePortMockRecorder) SPP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SPP", reflect.TypeOf((*MockDatabasePort)(nil).SPP))
}

// Sekolah mocks base method.
func (m *MockDatabasePort) Sekolah() outbound_port.SekolahPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sekolah")
	ret0, _ := ret[0].(outbound_port.SekolahPort)
	return ret0
}

// Sekolah indicates an expected call of Sekolah.
func (mr *MockDatabasePortMockRecorder) Sekolah() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sekolah", reflect.TypeOf((*MockDatabasePort)(nil).Sekolah))
}

// Subscription mocks base method.
func (m *MockDatabasePort) Subscription() outbound_port.SubscriptionDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscription")
	ret0, _ := ret[0].(outbound_port.SubscriptionDatabasePort)
	return ret0
}

// Subscription indicates an expected call of Subscription.
func (mr *MockDatabasePortMockRecorder) Subscription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscription", reflect.TypeOf((*MockDatabasePort)(nil).Subscription))
}

// Tenant mocks base method.
func (m *MockDatabasePort) Tenant() outbound_port.TenantDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tenant")
	ret0, _ := ret[0].(outbound_port.TenantDatabasePort)
	return ret0
}

// Tenant indicates an expected call of Tenant.
func (mr *MockDatabasePortMockRecorder) Tenant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tenant", reflect.TypeOf((*MockDatabasePort)(nil).Tenant))
}

// User mocks base method.
func (m *MockDatabasePort) User() outbound_port.UserDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(outbound_port.UserDatabasePort)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockDatabasePortMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockDatabasePort)(nil).User))
}

// WhatsApp mocks base method.
func (m *MockDatabasePort) WhatsApp() outbound_port.WhatsAppDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhatsApp")
	ret0, _ := ret[0].(outbound_port.WhatsAppDatabasePort)
	return ret0
}

// WhatsApp indicates an expected call of WhatsApp.
func (mr *MockDatabasePortMockRecorder) WhatsApp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhatsApp", reflect.TypeOf((*MockDatabasePort)(nil).WhatsApp))
}

// MockDatabaseExecutor is a mock of DatabaseExecutor interface.
type MockDatabaseExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseExecutorMockRecorder
}

// MockDatabaseExecutorMockRecorder is the mock recorder for MockDatabaseExecutor.
type MockDatabaseExecutorMockRecorder struct {
	mock *MockDatabaseExecutor
}

// NewMockDatabaseExecutor creates a new mock instance.
func NewMockDatabaseExecutor(ctrl *gomock.Controller) *MockDatabaseExecutor {
	mock := &MockDatabaseExecutor{ctrl: ctrl}
	mock.recorder = &MockDatabaseExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseExecutor) EXPECT() *MockDatabaseExecutorMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockDatabaseExecutor) Exec(query string, args ...interface{}) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDatabaseExecutorMockRecorder) Exec(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDatabaseExecutor)(nil).Exec), varargs...)
}

// Prepare mocks base method.
func (m *MockDatabaseExecutor) Prepare(arg0 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", arg0)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockDatabaseExecutorMockRecorder) Prepare(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockDatabaseExecutor)(nil).Prepare), arg0)
}

// Query mocks base method.
func (m *MockDatabaseExecutor) Query(arg0 string, arg1 ...interface{}) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDatabaseExecutorMockRecorder) Query(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDatabaseExecutor)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockDatabaseExecutor) QueryRow(arg0 string, arg1 ...interface{}) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDatabaseExecutorMockRecorder) QueryRow(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDatabaseExecutor)(nil).QueryRow), varargs...)
}
