// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/evolution_api.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWhatsAppClientPort is a mock of WhatsAppClientPort interface.
type MockWhatsAppClientPort struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppClientPortMockRecorder
}

// MockWhatsAppClientPortMockRecorder is the mock recorder for MockWhatsAppClientPort.
type MockWhatsAppClientPortMockRecorder struct {
	mock *MockWhatsAppClientPort
}

// NewMockWhatsAppClientPort creates a new mock instance.
func NewMockWhatsAppClientPort(ctrl *gomock.Controller) *MockWhatsAppClientPort {
	mock := &MockWhatsAppClientPort{ctrl: ctrl}
	mock.recorder = &MockWhatsAppClientPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsAppClientPort) EXPECT() *MockWhatsAppClientPortMockRecorder {
	return m.recorder
}

// ConnectInstance mocks base method.
func (m *MockWhatsAppClientPort) ConnectInstance(ctx context.Context, instanceName, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectInstance", ctx, instanceName, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectInstance indicates an expected call of ConnectInstance.
func (mr *MockWhatsAppClientPortMockRecorder) ConnectInstance(ctx, instanceName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectInstance", reflect.TypeOf((*MockWhatsAppClientPort)(nil).ConnectInstance), ctx, instanceName, token)
}

// CreateInstance mocks base method.
func (m *MockWhatsAppClientPort) CreateInstance(ctx context.Context, instanceName, token string) (*model.WhatsAppSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, instanceName, token)
	ret0, _ := ret[0].(*model.WhatsAppSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockWhatsAppClientPortMockRecorder) CreateInstance(ctx, instanceName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockWhatsAppClientPort)(nil).CreateInstance), ctx, instanceName, token)
}

// DeleteInstance mocks base method.
func (m *MockWhatsAppClientPort) DeleteInstance(ctx context.Context, instanceName, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, instanceName, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockWhatsAppClientPortMockRecorder) DeleteInstance(ctx, instanceName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockWhatsAppClientPort)(nil).DeleteInstance), ctx, instanceName, token)
}

// FetchInstance mocks base method.
func (m *MockWhatsAppClientPort) FetchInstance(ctx context.Context, instanceName, token string) (*model.WhatsAppSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchInstance", ctx, instanceName, token)
	ret0, _ := ret[0].(*model.WhatsAppSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchInstance indicates an expected call of FetchInstance.
func (mr *MockWhatsAppClientPortMockRecorder) FetchInstance(ctx, instanceName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchInstance", reflect.TypeOf((*MockWhatsAppClientPort)(nil).FetchInstance), ctx, instanceName, token)
}

// LogoutInstance mocks base method.
func (m *MockWhatsAppClientPort) LogoutInstance(ctx context.Context, instanceName, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutInstance", ctx, instanceName, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutInstance indicates an expected call of LogoutInstance.
func (mr *MockWhatsAppClientPortMockRecorder) LogoutInstance(ctx, instanceName, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutInstance", reflect.TypeOf((*MockWhatsAppClientPort)(nil).LogoutInstance), ctx, instanceName, token)
}

// SendMessage mocks base method.
func (m *MockWhatsAppClientPort) SendMessage(ctx context.Context, instanceName, token, phone, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, instanceName, token, phone, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockWhatsAppClientPortMockRecorder) SendMessage(ctx, instanceName, token, phone, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockWhatsAppClientPort)(nil).SendMessage), ctx, instanceName, token, phone, message)
}
